### ISSUE TITLE
Mostly just a question.

### ISSUE THREAD

**Issue by ThePsyKai** [FabianFG/CUE4Parse#35]
So I'm looking at the files and I don't see anything mentioning umap files. I'm trying to make a Blender plugin that imports Umaps (it is in python), but I don't see how Cue4Parse handles Umaps. Sorry for being a bother ^^'

**Comment by FabianFG** [comment]
Umaps are parsed as normal uassets. They do have additional in the ULevel's but we don't support parsing landscape data yet. The different building actors should be there though

**Comment by Amrsatrio** [comment]
Check https://github.com/Amrsatrio/BlenderUmap2 for an existing solution that uses CUE4Parse. The python script is in https://github.com/Amrsatrio/BlenderUmap

**Comment by Kein** [comment]
@Amrsatrio 
Does not seems to work with WorldComposited levels

**Comment by Opa-** [comment]
@FabianFG I'm trying to convert .umap files from a game into 3D models in order to create GIS pictures of them but most of the important data are Spline Mesh Component and doesn't seems to be handled by this parsing library. 
Do you consider these Spline Mesh Component to be part of what you are referring to as "landscape data" ?
And do you know if parsing these landscape data is a feature that is looked into for the near future ?
