### ISSUE TITLE
Exporting and looping over exports causes Segmentation fault

### ISSUE THREAD

**Issue by xNocken** [FabianFG/CUE4Parse#49]
I made a program that loops over every map and saves all the objects i want. This worked without any problems in earlier Fortnite versions. But since the 21.0 Fortnite update when loading the map `fortnitegame/plugins/gamefeatures/parallelgameplay/content/leveloverlays/artemis_poi_dailybugle_002_paralleloverlay.umap` and then looping over the exports using foreach throws some `System.OutOfMemoryException` which is then followed by a segmentation fault. The program uses about 1gb of ram and my system has more than 10gb available.

I already used the newest patches that were commited on June 5th.

My code
```cs
var provider = new DefaultFileProvider(_gameDirectory, SearchOption.TopDirectoryOnly, true, new VersionContainer(EGame.GAME_UE5_LATEST));

provider.Initialize(); 
provider.SubmitKey(new FGuid(), new FAesKey(_aesKey));
provider.LoadMappings(); 

provider.TryLoadPackage("fortnitegame/plugins/gamefeatures/parallelgameplay/content/leveloverlays/artemis_poi_dailybugle_002_paralleloverlay.umap", out var package);

var exports = package.GetExports();

foreach (var export in exports) { // here is where it crashes
}
```

Dotnet version: 6.0.202
OS: Ubuntu 20.04.4

**Comment by iAmAsval** [comment]
I investigated this issue and turns out it never actually worked in previous versions, it simply wasn't crashing *yet*
Nonetheless, this is an interesting issue as I couldn't find any difference between the UE source code and CUE4Parse

In the image below, we can see that:

- `#ff9933` is actually `4` aka [LODData Length](https://github.com/FabianFG/CUE4Parse/blob/instancedstaticmeshcomponent/CUE4Parse/UE4/Assets/Exports/Component/StaticMesh/UStaticMeshComponent.cs#L13)
- `#9933ff` are the 4 [FStripDataFlags](https://github.com/FabianFG/CUE4Parse/blob/instancedstaticmeshcomponent/CUE4Parse/UE4/Assets/Exports/Component/StaticMesh/FStaticMeshComponentLODInfo.cs#L47)
- After each of these FStripDataFlags, we are supposed to get a GUID, however, we have 2 interesting values:

1. `0xFFFF` aka `MAX_UNSIGNED_SHORT`
2. an Integer representing whatever value it is supposed to represent
3. then we have the 16 bytes GUID as expected
4. and the [PaintedVertices Length](https://github.com/FabianFG/CUE4Parse/blob/instancedstaticmeshcomponent/CUE4Parse/UE4/Assets/Exports/Component/StaticMesh/FStaticMeshComponentLODInfo.cs#L67)
- after LODData we get `#ff0000` supposedly the size of [PerInstanceSMData](https://github.com/FabianFG/CUE4Parse/blob/instancedstaticmeshcomponent/CUE4Parse/UE4/Assets/Exports/Component/StaticMesh/UInstancedStaticMeshComponent.cs#L23) but it's actually multiplied by 2 for some reason
- furthermore, it looks like we are supposed to [skip 4 bytes](https://github.com/FabianFG/CUE4Parse/blob/instancedstaticmeshcomponent/CUE4Parse/UE4/Assets/Exports/Component/StaticMesh/UStaticMeshComponent.cs#L14) after LODData, else the size of PerInstanceSMData is `1` which makes even less sense to me. Doing so makes `1` the [bCooked Value](https://github.com/FabianFG/CUE4Parse/blob/instancedstaticmeshcomponent/CUE4Parse/UE4/Assets/Exports/Component/StaticMesh/UInstancedStaticMeshComponent.cs#L20)

![image](https://user-images.githubusercontent.com/26126862/173028958-7c393622-001c-4977-ba0a-2ac1064d6f8f.png)

As said above, some of those values aren't in the UE source code:

- MAX_UNSIGNED_SHORT
- the Integer after it
- PerInstanceSMData Size * 2

and the changes made might break other assets or other games. I can't guarantee that these will be merged in the main branch someday.

**Comment by xNocken** [comment]
I just tested your change and it seems to be fixed. I managed to parse all maps including all overlays and weapons without any problems
